### ISSUE TITLE
Compact the team image file size

### ISSUE THREAD

**Issue by rockacola** [CityOfZion/cityofzion-website#18]
I've noticed a few of the team images are over 100KB which seems unnecessarily large.

May I recommend (or I can PR it) parse all team images through https://tinypng.com/ for "almost-lossless" compression?

Example compression performance of a random member photo:

<img width="996" alt="image" src="https://user-images.githubusercontent.com/146148/37755703-ae4d10a0-2dfa-11e8-9ca0-5312a4fb1d94.png">

**Comment by rockacola** [comment]
If you are not comfortable using 3rd party SaaS, there's also `optipng` doing the same thing but slightly worse than TinyPNG.

It's available through `brew`, `apt-get` or `npm`.

**Comment by metachris** [comment]
Thanks for the suggestion. I ran all image through an image optimizer. Which image could be further reduced?

**Comment by Woodehh** [comment]
@rockacola the images are the originals in the repository. When deploying; we run an Image optimizer in Gulp and @metachris compresses them afterwards with a crusher.

The images are ~40kb each in the live repository.

However, i agree that we should probably also have that crusher in the Gulpfile. Just to cut a custom step and make it more standardized. Because that's what we want :)

@metachris What do you think of using tinypng in the Gulp build file?

**Comment by rockacola** [comment]
> Not sure we should use a lossy one.

For photos, IMO I see no harms especially with benefits of saving image file sizes on a simple page where we know to have 50+ profile photos to display.

**Comment by metachris** [comment]
weirdly, mozjpeg or jpegtran don't reduce the file size of the images:

    $ ls -alh alexguba.jpg
    -rw-r--r-- 1 chris staff 95K Mar 21 20:22 alexguba.jpg
    $ jpegtran -copy none -optimize -progressive -outfile test.jpg alexguba.jpg
    $ ls -alh test.jpg
    -rw-r--r-- 1 chris staff 95K Mar 22 13:07 test.jpg

**Comment by metachris** [comment]
how can we automate this better?

**Comment by metachris** [comment]
Aaah, ImageMagick for the win!

    $ convert -strip -interlace Plane -gaussian-blur 0.05 -quality 85% alexguba.jpg test.jpg
    $ ls -alh test.jpg
    -rw-r--r-- 1 chris staff 26K Mar 22 13:07 test.jpg
    $ convert -strip -interlace Plane -gaussian-blur 0.05 -quality 80% alexguba.jpg test.jpg
    $ ls -alh test.jpg
    -rw-r--r-- 1 chris staff 22K Mar 22 13:07 test.jpg

Please use imagemagick with the 80% setting. I'll update the existing images.

**Comment by metachris** [comment]
Converted the images with the above command. Before:

    $ du --si -s team-images/
    4.4M	team-images/

After:

    $ du --si -s team-images/
    959k	team-images/

**Comment by Woodehh** [comment]
Cool, i'll include the task in Gulp. Imagemagick has a gulp plugin, which is nice!

**Comment by Woodehh** [comment]
This issue is resolved in the current master branch
