### ISSUE TITLE
Add proper OpenGraph and Twitter meta tags

### ISSUE THREAD

**Issue by metachris** [CityOfZion/cityofzion-website#2]
So it looks nice when shared.

Currently:
![screen shot 2018-03-12 at 13 15 36](https://user-images.githubusercontent.com/116939/37283242-8d7db2a4-25f7-11e8-81cb-6e4f4e43485b.png)

**Comment by Woodehh** [comment]
This issue can be closed in favour of the new website. It's added now.

see PR #14
