### ISSUE TITLE
Default zoom is not set to full page on mobile devices

### ISSUE THREAD

**Issue by drptbl** [CityOfZion/cityofzion-website#4]
**Device:**
iPhone 6S (iOS 11.2.6)

**Browsers:**
Safari and Chrome

**Description:**
After going to cityofzion website on new browser tab for first time default zoom is not set to full page.

**Video:**
https://drive.google.com/file/d/1juD2ELbgMhIpv1_v3AVtpoeuz-wtoOZK/view

**Screenshots:**
![chrome](https://user-images.githubusercontent.com/8177587/37307254-97f371cc-263a-11e8-9ffa-5a9dd71a8bbc.png)
![safari](https://user-images.githubusercontent.com/8177587/37307256-9956492c-263a-11e8-966b-4e8b27a68612.png)

**Comment by metachris** [comment]
Thank you very much for the detailed report!

Perhaps anyone can figure this out and create a PR? <3

**Comment by Woodehh** [comment]
This issue can be closed in favour of the new Bootstrap framework. It's added now.

**Comment by drptbl** [comment]
@Woodehh Do you mean that it was fixed? I've just re-tested this issue and it still occurs. Was it released to production already?

**Comment by Woodehh** [comment]
I'm sorry. The new page for testing is: http://cityofzion.io/landing-new/

**Comment by drptbl** [comment]
@Woodehh Yes, it's fixed 👍 . Thank you!

**Comment by metachris** [comment]
Great, thanks to both of you! Let's close this issue when we update the homepage with the new landing-new, soon (tm)

**Comment by Woodehh** [comment]
@drptbl Can you confirm the issue you were having is fixed on: http://cityofzion.io/ If so we can close the issue! :)

**Comment by drptbl** [comment]
@Woodehh Re-tested, everything works as it should. Thanks again 🤝 .

**Comment by Woodehh** [comment]
AWESOME!

Closed
