### ISSUE TITLE
Neon Wallet goes blank

### ISSUE THREAD

**Issue by redtoppaul** [CityOfZion/cityofzion-website#63]
Can anybody tell me why my neon wallet suddenly goes blank and if i can stop it 
updated to 0.2.5 using ledger nano s
Thanks

**Comment by Woodehh** [comment]
Hi mate!

Thanks for reachign out, however, this is not the right place to do so. Your best bet would be to go to our Discord and post your question there.

You can visit our discord channel (here)[https://discordapp.com/invite/b8QNXwD].

Hope this helps you out mate!

Cheers
