### ISSUE TITLE
Go https://cityofzion.io

### ISSUE THREAD

**Issue by JackdeHeer** [CityOfZion/cityofzion-website#67]
CoZ should add a SSL to cityofzion.io because some browsers will mark websites as 'not secure' or might even give a privacy error -> warning. 

Other than that it's also beneficial for SEO.

**Comment by Woodehh** [comment]
@metachris This is something you should be able to do so (as described here)[https://help.github.com/articles/troubleshooting-custom-domains/#https-errors].

**Comment by metachris** [comment]
Seems easy to enforce HTTPS: https://help.github.com/articles/securing-your-github-pages-site-with-https/

But we currently have some problem with the domain DNS configuration -- i'm on it and will try to enforce HTTPS asap.

**Comment by Woodehh** [comment]
LOL that's the link i've attached in my message 🔮

**Comment by metachris** [comment]
Fixed now. Thanks for the heads-up.
