### ISSUE TITLE
Need Your HELP : Some one broke into my NEO wallet and transferred all my NEO coins

### ISSUE THREAD

**Issue by prestiva** [CityOfZion/cityofzion-website#68]
Hi City Of Zion Team,

I need your HELP PLEASE. Day before yesterday some one broke into my NEON wallet. I need your guidance and help.

Can you please tell me how to track, who/which IP moved it my close to 3000 NEO coins. I really need your advice. Is they any way you can block/hold the movement of the coins.

I have attached the detail information for your reference.

[NEO tokens.docx](https://github.com/CityOfZion/cityofzion-website/files/2291473/NEO.tokens.docx)

If you have any question, want to reach out to me, please email at muralivenkatesh2018@gmail.com

Thanks for your HELP

**Comment by Woodehh** [comment]
Hi mate!

Thanks for reaching out and I'm sorry this has happened to you. However, the best chance to find information regarding this malicious transaction would be to address people in the Discord and post your question there.

Please be advised, the chances of getting your funds back are close to nil. Also to find out who performed the transaction is not something I would see happening ver quickly, sorry to be the bearer of this bad news. 

You can visit our Discord group (here)[https://discordapp.com/invite/b8QNXwD].

Hope this helps you out mate! Good luck on your search to justice.

Best
