### ISSUE TITLE
Neo testnet coins are gone to 0 from 1000 after 15 days withput initiating the transaction 

### ISSUE THREAD

**Issue by Anil402** [CityOfZion/cityofzion-website#70]
Hi,
As I applied for neo testnet coins on 18 Aug, and I got the assets from your side on 23 Aug.

From that day we have started the required integration.

On 5 Sept I have restarted the neo syncing by using this command  

dotnet neo-cli.dll --rpc --log
On 7 Sept all testnet coins from my wallet are transferred to an external wallet address, but the issue is that we have not initiated any transaction from our side

I want to know the reason what is actually the problem with neo assets, can you please explain in details.

We are at the last stage of our exchange project.

**Comment by canesin** [comment]
this is not NEO page.

**Comment by metachris** [comment]
If your neo node is having an open wallet, it must not be accessible from the internet, else there are hackers around that just wait to steal your funds if you run it unsecured.
